### ISSUE TITLE
Example isn't working, error "Unexpected close tag"

### ISSUE THREAD

**Issue by benbuckman** [vesln/teacher#1]
I'm exploring the use of your module, but when I ran the example to see how it works, it didn't correct the first misspelling as it should have. Outputting the `err` parameter in the callbacks shows the error "Unexpected close tag" being thrown.

**Comment by vesln** [comment]
Hey, thank you for opening the issue. Everything seems fine here. I've tested both the code in examples/ and that in Readme.md on node 0.6.x. Also the tests are running just fine. Can you provide a gist with your code and the version of node that you're running. Thanks!

**Comment by davidsilvasmith** [comment]
I'm getting a lot of unexpected closing tags too. In my case I'm running it through grunt. It processes the first file ok and then fails later. If I delete the first file it processes the next one OK. So it is a bug somewhere in the pipeline.
