### ISSUE TITLE
Custom dictionary

### ISSUE THREAD

**Issue by offsky** [vesln/teacher#2]
It would be nice to be able to supply a custom dictionary file so that teacher will ignore spelling errors that are really just my name, or product name that I know isn't misspelled.

**Comment by offsky** [comment]
Is this implemented or are you marking this as wontfix?

**Comment by vesln** [comment]
Sorry, forgot to paste the comment, which was:

> Sadly, I'm not really maintaining this anymore. If u are interested in taking over - lmk!
