### ISSUE TITLE
503 errors cause cryptic error messages to be returned

### ISSUE THREAD

**Issue by erikvold** [vesln/teacher#3]
When using this code:

```
teacher.check("blah", function(err, data) {
  console.log(err);
})
```

And when this data is being return from after the deadline (which I suppose is a 503 error):

```
<html>
<head><title>503 Service Temporarily Unavailable</title></head>
<body bgcolor="white">
<center><h1>503 Service Temporarily Unavailable</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

Then `err` is this:

Uncaught AssertionError: expected [Error: Unexpected close tag
Line: 5
Column: 7
Char: >] to equal null

Which is pretty unhelpful, at first I thought there was some issue with the string that I was send to be checked..

**Comment by vesln** [comment]
Sadly, I'm not really maintaining this anymore. If u are interested in taking over - lmk!

**Comment by erikvold** [comment]
@vesln sure I can help out!
